name: phntmxyz_ios_publishing_sidekick_plugin
description: Generated sidekick plugin (template shared-code)
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dcli: ^2.2.0
  deep_pick: ^1.0.0
  plist_parser: ^0.0.9
  sidekick_core: ^2.0.0
  sidekick_vault: ^1.0.0
  xml: ^6.1.0

dev_dependencies:
  lint: ^1.5.0
  sidekick_plugin_installer: ^1.1.0
