name: phntmxyz_ios_publishing_sidekick_plugin
description: Generated sidekick plugin (template shared-code)
version: 0.4.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  dcli: ^7.0.2
  deep_pick: ^1.0.0
  plist_parser: ^0.0.9
  pubspec_manager: ^1.0.1
  sidekick_core: ^3.0.0-preview.5
  sidekick_vault: ^1.3.0
  xml: ^6.1.0

dev_dependencies:
  lint: ^2.0.0
  sidekick_plugin_installer: ^1.3.0
  test: ^1.24.0