name: On Push
on: [push]
jobs:
  build:
      uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
      with:
        dart_sdk: "stable"
        platform: "vm"
        min_coverage: 0